name: Fast Firmware Build

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-firmware:
    runs-on: ubuntu-latest
    container: espressif/idf:release-v5.0
    steps:
      - uses: actions/checkout@v4
      - name: Build esp-hosted
        run: |
          mkdir -p build/esp-hosted
          cd build/esp-hosted
          git clone https://github.com/jcmvbkbc/esp-hosted .
          git checkout e2f19edab6c5bec988346906412cb8e7443661db
          cd esp_hosted_ng/esp/esp_driver
          git submodule update --init --depth 1
          cd "$GITHUB_WORKSPACE"
          ./new-files/toplevel/apply-local-changes.sh esp-hosted
          cd build/esp-hosted/esp_hosted_ng/esp/esp_driver/network_adapter
          idf.py set-target esp32s3
          idf.py build
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: fast-network-adapter
          path: build/esp-hosted/esp_hosted_ng/esp/esp_driver/network_adapter/build/network_adapter.bin
